# 💖 Support Black Myth: Wukong Combat Guide Development

# GitHub Sponsors (preferred method)
github: [Black-Myth-Wukong-Combat-Secrets]

# Alternative funding platforms
# patreon: blackmythwukong
# ko_fi: blackmythwukong
# buy_me_a_coffee: wukongguide

# Cryptocurrency (for international supporters)
# bitcoin: 
# ethereum: 

# Custom funding URLs
custom: ['https://black-myth-wukong-combat-secrets.github.io/donate', 'https://discord.gg/blackmythwukong'] 